# Generated by Django 3.0.3 on 2020-05-09 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rec_sys', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipe',
            name='date',
        ),
        migrations.AddField(
            model_name='category',
            name='old_id',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='recipe',
            name='old_id',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tag',
            name='old_id',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
