# Generated by Django 3.0.3 on 2020-05-15 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rec_sys', '0002_auto_20200509_1450'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='similar',
            field=models.TextField(blank=True, max_length=10000, null=True),
        ),
        migrations.AlterField(
            model_name='history',
            name='view_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
